config/routes.rb
Todos::Application.routes.draw do

    root to: 'high_voltage/pages#show', id: 'homepage'

    resource :session, only: [:create]
    resources :todos, only: [:index, :new, :create]

end

app/models/todo.rb
class Todo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def sign_in_as(email)
    session[:current_email] = email
  end

  def current_user
    OpenStruct.new(email: session[:current_email], todos: Todo.all)
  end

  helper_method :current_user
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController 
  def create
    session[:current_email] = params[:session][:email_address] 
    redirect_to todos_path
  end 
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController 
  def index 
    @todos = current_user.todos
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(params[:todo].permit(:description, :owner_email)).save
    redirect_to todos_path 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todos</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class='welcome'>Welcome, <%= current_user.email %></p>
<%= yield %>

</body>
</html>

app/views/pages/homepage.html.erb
<p data-role='description'>This is an app to manage todos</p>

<%= form_for :session, url: session_path do |form| %>
  <%= form.label :email_address %>
  <%= form.text_field :email_address %>
  <%= form.submit 'Sign In' %>

<% end %>

app/views/todos/index.html.erb
<ul>
<% @todos.each do |todo| %>
  <li class="todo"><%= todo.description %></li>
  <% end %>
</ul>
<%= link_to 'Add a new todo', new_todo_path %>

app/views/todos/new.html.erb
<%= form_for @todo do |form| %>
  <%= form.label :description %>
  <%= form.text_field :description %>
  <%= form.submit 'Create todo' %>

<% end %>